
import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'

import { ClerkProvider } from '@clerk/nextjs'
import { QueryProvider } from "@/components/shared/queryProvider";

const poppins = Poppins({ 
  subsets: ["latin"],
  weight: ['300','400', '500','600', '700'],
  variable: '--font-poppins' 
});

export const metadata: Metadata = {
  title: "dvizh.kz",
  description: "Generated by create next app",
  icons:{
    icon: '/bilon/public/assets/icons/iconview.png'
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <ClerkProvider >
          <QueryProvider>

    <html lang="en">
       <head>
      <script src="https://telegram.org/js/telegram-web-app.js"></script>
      </head> 
      <body className={`${poppins.variable} `}>{children}</body> 

     
    </html>
    </QueryProvider>

    </ClerkProvider>
   

  );
}
  